menu:
  Home: /
  # Archives: /archives
  About: /about

widgets:
- search
- recent_posts
- tag
- tagcloud
- links

#### Links
links:
  阮一峰的网络日志: http://www.ruanyifeng.com/blog
  陈浩的技术博客: https://coolshell.cn
  云风的技术博客: https://blog.codingnow.com
  测开工程师的技术博客: https://debugtalk.com
  菜鸟教程: https://www.runoob.com
  敏捷管理平台: https://taiga.io
  代码托管平台: https://gitea.io
  持续交付平台: https://drone.io
  接口管理平台: https://www.apifox.cn
  性能测试平台: https://www.locust.io
  安全测试平台: https://www.acunetix.com
  代码静态分析平台: https://www.sonarqube.org
  知识分享: https://gohugo.io  
  在线绘图: https://www.draw.io
excerpt_link: Read More ›

#### Image
imglogo:
  enable: true         ## 是否开启网站的logo，标题左边的logo。
  src: img/logo.png   ## 图片放在`/concise/source/imgs`目录下,使用.svg和.png格式的图片.
favicon: img/favicon.ico   ## 浏览器标签上显示的图片,放在`/concise/source/imgs`下.

author_img_enable: true     ## 是否开启作者头像,左下角会旋转头像.
author_img: imgs/author.jpg ## 作者头像的路径,以../comcise/source/文件夹为根路径,如果放在imgs文件夹下,格式如本人范例


twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

google_analytics:

duoshuo_enable: true    ##不想用，改为false即可
duoshuo_shortname: zhoukuo

#### Fancybox   ##图片效果
fancybox: true 
