# Header
menu:
  Home: /
  Archives: /archives

# Content
excerpt_link: Read More
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  阮一峰的网络日志: http://www.ruanyifeng.com/blog/
  王  垠: http://www.yinwang.org/
  Go语言圣经: https://docs.ruanjiadeng.com/gopl-zh/
  Golang中国: http://www.golangtc.com/
  乐编程: http://www.01happy.com/
  我的开源中国: http://my.oschina.net/zhoukuo/blog
  我的GitHub: https://github.com/zhoukuo
# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: zhoukuo

# Baidu share
baidushare: true